name: PocketMorph
author: HotshotHD VCraftPE
version: 1.1.0
description: Morph into your favourite mobs!
main: pocketmorph\PocketMorph
api: 2.0.0
commands:
  morph:
    description: Transform into a mob
    permission: morph.command

permissions:
  morph.command:
    description: Allows using all PocketMorph commands
    default: op
